# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a65e0ffbdf5c7951d9ff755d25e7bc9509547dbae4195bcbc126cab7fc1e9b041b033ef77b72501999bbfc5a6332693a6f2a9911b4de0d8b94bd01247db89176

test:
  secret_key_base: bc52d6736f7bb7533b44ebd0b4644af120fea4ce7330b522670e4151b13e2c3ef45cf0ee4f00d023c28dc6ba6d88c1731c96dd620a6c426e9f3adfcf11702689

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
